workspace 'EasyPeasy'


target 'Demo' do
  project 'EasyPeasy.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end

target 'Tests' do
  project 'EasyPeasy.xcodeproj'
  pod 'EasyPeasy', :path => '../'
end
